# e2e setting
encoder: slowfast
slowfast_depth: 50
pretrained_model: https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb/slowfast_r50_256p_4x16x1_256e_kinetics400_rgb_20200728-145f1097.pth

# model setting
enc_layers: 4
dec_layers: 4
dim_feedforward: 1024
num_queries: 40

# data setting
dataset_name: thumos14
feature: img10fps
online_slice: true
slice_len: 256
slice_overlap: 0.75
test_slice_overlap: 0.25
input_type: image

# training setting (not finialized)
lr: 0.0001
batch_size: 4


# output
output_dir: outputs/thumos14_e2e_slowfast_tadtr

